# Generated by Django 4.1.3 on 2022-12-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("excel_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="excel_data",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("symbol", models.CharField(max_length=255)),
                ("order_price", models.FloatField()),
                ("stop_loss", models.FloatField()),
                ("take_profit", models.FloatField()),
                ("contract_type", models.CharField(max_length=10)),
                ("signal", models.BooleanField()),
                ("total_position", models.IntegerField()),
                ("initial_margin", models.IntegerField()),
                ("total_deposit", models.FloatField()),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
