# Generated by Django 4.1.3 on 2022-12-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("excel_api", "0002_excel_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstantDatas",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("signal", models.BooleanField()),
                ("total_position", models.IntegerField()),
                ("initial_margin", models.IntegerField()),
                ("total_deposit", models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name="excel_data",
            name="leverage",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="excel_data",
            name="token_quantity",
            field=models.FloatField(default=0),
        ),
    ]
