# Generated by Django 4.1.3 on 2022-12-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("excel_api", "0003_constantdatas_excel_data_leverage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constantdatas",
            name="initial_margin",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="constantdatas",
            name="total_position",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="excel_data", name="initial_margin", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="excel_data", name="total_position", field=models.FloatField(),
        ),
    ]
