# Generated by Django 4.1.3 on 2022-12-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_api', '0005_exceldata_delete_excel_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldata',
            name='liquidation_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='percent_of_loss',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='exceldata',
            name='valid_action',
            field=models.BooleanField(default=True),
        ),
    ]
