# Generated by Django 4.1.3 on 2022-12-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_api', '0006_exceldata_liquidation_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldata',
            name='reward_risk',
            field=models.FloatField(default=0),
        ),
    ]
